config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  mount Sidekiq::Web => '/sidekiq'

  root 'weather#show'
  resources :weather
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/location.rb
class Location < ApplicationRecord
  has_many :weather_reports

  validates :city, presence: true
  validates :country, presence: true
end

app/models/weather_report.rb
class WeatherReport < ApplicationRecord
  belongs_to :location

  validates :weather, presence: true
  validates :description, presence: true
  validates :temp, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
end

app/controllers/weather_controller.rb
class WeatherController < ApplicationController
  def index
    items = params[:items]
    items ||= 10
    @pagy, @weather = pagy(WeatherReport.all, items:)

    respond_to do |format|
      format.html
      format.json do
        render json: {
          data: ActiveModel::Serializer::CollectionSerializer.new(
            @weather, serializer: WeatherReportSerializer
          ),
          pagy: @pagy
        }
      end
    end
  end

  def show
    @weather = WeatherReport.last  # get latest data
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend

  def format_date_time(date_time)
    date_time.strftime('%A, %B %d, %Y %H:%M')
  end

  def icon_url(icon_code)
    "https://openweathermap.org/img/wn/#{icon_code}@2x.png"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WeatherApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto my-10 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/weather/_row.html.erb
<tr class="bg-white border-b">
    <th
      scope="row"
      class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap"
    >
      <%= format_date_time(element.created_at)%>
    </th>
    <td class="px-6 py-4"><%= element.weather%></td>
    <td class="px-6 py-4"><%= element.description%></td>
    <td class="px-6 py-4"><%= element.temp%></td>
    <td class="px-6 py-4"><%= element.temp_min%></td>
    <td class="px-6 py-4"><%= element.temp_max%></td>
    <td class="px-6 py-4"><%= element.pressure%></td>
    <td class="px-6 py-4"><%= element.humidity%></td>
  </tr>

app/views/weather/_table.html.erb
<table class="w-full text-sm text-left text-gray-500">
    <thead class="text-xs text-gray-700 uppercase bg-gray-50">
      <tr>
        <th scope="col" class="px-6 py-3">Date Time</th>
        <th scope="col" class="px-6 py-3">weather</th>
        <th scope="col" class="px-6 py-3">description</th>
        <th scope="col" class="px-6 py-3">temp</th>
        <th scope="col" class="px-6 py-3">temp_min</th>
        <th scope="col" class="px-6 py-3">temp_max</th>
        <th scope="col" class="px-6 py-3">pressure</th>
        <th scope="col" class="px-6 py-3">humidity</th>
      </tr>
    </thead>
    <tbody>
      <% @weather.each_with_index do |element, index| %>
        <%= render "row", element: , index: %>
      <% end %>
    </tbody>
  </table>

app/views/weather/index.html.erb
<div class="flex-col justify-center items-center w-full gap-8">
  <div class="text-4xl font-bold">
    <p>Weather Data</p>
  </div>
  
  <div class="relative overflow-x-auto w-full">
    <%= render "table"%>
    <div class="w-full flex justify-center items-center mt-6">
      <%== pagy_nav(@pagy) if @pagy.pages > 1 %>
    </div>
  </div>  
</div>

app/views/weather/show.html.erb
<div class="flex justify-center items-center w-full h-[80vh]">
  <div class="shadow-lg p-12 bg-gray-800 rounded-md text-white">
    <div class="text-3xl">
      <h1><%= @weather.location.city %></h1>
    </div>

    <img src= <%= icon_url(@weather.icon)%> alt="Weather Icon" class="w-32 h-auto">

    <div class="mb-4">
      <h2 class="text-2xl"><%= @weather.weather %></h2>
      <h3><%= @weather.description %></h3>
      <h1><%= @weather.temp_min %><sup>°</sup>C - <%= @weather.temp_max %><sup>°</sup>C </h1>
    </div>

    <div class="flex justify-center items-center w-full">
        <%= link_to 'view All', weather_index_path, class: 'text-white bg-transparent border-2 border-blue-800 hover:bg-blue-800 font-medium rounded-lg text-sm px-5 py-2.5' %>
    </div>
  </div>
</div>